# Generated by Django 4.1.6 on 2023-02-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=4096, verbose_name='Описание')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in progress', 'В процессе'), ('done', 'Сделано')], default='new', max_length=16, verbose_name='Статус')),
                ('deadline', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
