# Generated by Django 4.1.6 on 2023-02-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='full_description',
            field=models.TextField(blank=True, max_length=4096, null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=128, verbose_name='Описание'),
        ),
    ]
